spring:
  profiles: default

zuul:
  routes:
    employee:
      path: /employee/**
      url: http://managment-dev-dev/employee
      service-id: /employee/**

    attendance:
      path: /attendance/**
      url: http://attendance-dev-dev/attendance
      service-id: /attendance/**

    salary:
      path: /salary/**
      url: http://salary-dev-dev/salary
      service-id: /salary/**
