spring:
  profiles: default

zuul:
  debug:
    request: true
  health:
    enabled: true
  routes:
    employee:
      path: /employee/**
      url: http://employee:8083/employee
      service-id: /employee/**

    attendance:
      path: /attendance/**
      url: http://attendance:8081/attendance
      service-id: /attendance/**

    salary:
      path: /salary/**
      url: http://salary:8082/salary
      service-id: /salary/**

    notification:
      path: /notification/**
      url: http://notification:8085/notification
      service-id: /notification/**
